import = ["~/.config/alacritty/themes/solarized_dark-private.toml"]

[font]
size = 14

[cursor]
style = "beam"

[font.normal]
family = "Source Code Pro Medium"
style = "Regular"

[env]
term = "xterm-256color"

[window]
opacity = 0.6
