# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# set custom format
add_newline = false
format='$character $directory$git_branch'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)]($style) '
symbol = ' '
style = "bold purple"