# SET THE KITTY THEME
include theme.conf

# set font family, size and attributes
font_family      FiraCode Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14

modify_font underline_position 2
modify_font underline_thickness 150%

# set global kitty attributes
term xterm-256color
background_opacity 1
confirm_os_window_close 0

# style tab bar
tab_bar_edge bottom
tab_bar_style powerline
tab_bar_background none
tab_title_template "{index} {tab.active_exe}"

