background {
    monitor =
    path = rgb(20,20,20)
}

general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

label {
    monitor =
    font_size = 50
    font_family = SF Pro Text Bold
    text = cmd[update:1000] echo "$TIME"
    color = rgb(69, 133, 136)
    position = 0, 420
    halign = center
    valign = center
}

label {
    monitor =
    font_size = 20
    font_family = SF Pro Text Bold
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgb(177, 98, 134)
    position = 0, 360
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 960, 540
    color = rgb(40, 40, 40)
    rounding = 15
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)
    halign = center
    valign = center
}

label {
    monitor =
    font_size = 30
    font_family = SF Pro Text Bold
    text = <span foreground="##cc241d">SCREEN LOCKED!</span>
    position = 0, 200
}

image {
    monitor =
    path = /mnt/rstation/dc-pfpx512.png
    border_size = 0
    size = 180
    rounding = 15
    position = -125, 0
}

shape {
    monitor =
    size = 250, 50
    color = rgb(80, 73, 69)
    rounding = 15
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)
    position = 115, 40
}

label {
    monitor =
    font_size = 20
    font_family = SF Pro Text Bold
    text = <span foreground="##ebdbb2">$USER</span>
    position = 90, 40
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0
    dots_size = 0.3 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = false
    outer_color = rgb(102, 92, 84)
    inner_color = rgb(80, 73, 69)
    font_color = rgb(235, 219, 178)
    font_family = SF Pro Text Bold
    fade_on_empty = false
    rounding = 10
    check_color = rgb(214, 93, 14)
    placeholder_text = <span foreground="##ebdbb2">Enter Password...</span>
    hide_input = false
    position = 115, -30
}
