#!/bin/bash

COLORSCHEME='prefer-dark'
CURSORTHEME='Bibata-Modern-Ice'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
    ${SCHEMA} colorscheme "$COLORSCHEME"
    ${SCHEMA} cursor-theme "$CURSORTHEME"
    ${SCHEMA} cursor-size 20
}

apply_themes
